In [25]:
#pandas is a python library. It contains the functions to load the data and process the same
#pandas is imported to load the input data from client into our program to develop the model
import pandas as pd

In [26]:
#reading the input csv file using the read_csv function in pandas library
dataset=pd.read_csv("Salary_Data.csv")
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [27]:
#indetify the input column and load the same to independent variable
independent=dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [28]:
#Identify the output/to predict column and load the same to dependent variable
dependent=dataset[["Salary"]]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [29]:
#sklearn is a python librarary. It contains the functions related to regression
#import the train_test_split function from the sklearn.model_selection package to split train and test dataset
from sklearn.model_selection import train_test_split
#train_test_split will get 4 inputs(independent, dependent, test_size,random_state)
#independent is a input dataset
#dependet is a output/to predict dataset
#test_size is a ratio of testdata
#random_state

#train_test_split will give 4 outputs(X_train, X_test, Y_train,Y_test) based on the test_size ratio
#X_train is a train dataset input
#Y_train is a train  output/to predict datset
#X_test is a test dataset input
#Y_test is a test  output/to predict datset
X_train, X_test, Y_train, Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

    YearsExperience
22              7.9
5               2.9
16              5.1
8               3.2
14              4.5
23              8.2
20              6.8
1               1.3
29             10.5
6               3.0
4               2.2
18              5.9
19              6.0
9               3.7
7               3.2
25              9.0
3               2.0
0               1.1
21              7.1
15              4.9
12              4.0
    YearsExperience
2               1.5
28             10.3
13              4.1
10              3.9
26              9.5
24              8.7
27              9.6
11              4.0
17              5.3
      Salary
22  101302.0
5    56642.0
16   66029.0
8    64445.0
14   61111.0
23  113812.0
20   91738.0
1    46205.0
29  121872.0
6    60150.0
4    39891.0
18   81363.0
19   93940.0
9    57189.0
7    54445.0
25  105582.0
3    43525.0
0    39343.0
21   98273.0
15   67938.0
12   56957.0
      Salary
2    37731.0
28  122391.0
13   57081.0
10   63218.0
26  116969.0
24  109431.0
27  112635.0
11   55794.0
17   83088.0

In [12]:
#import the LinearRegression function from sklearn.linear_model python package
#LinearRegression is a function used to create the Simple Linear regression model
from sklearn.linear_model import LinearRegression
#Assign the LinearRegression function to the regressor variable
regressor=LinearRegression()
#fit method is used to create a model. It will get the input and output/to predict output and create a model
regressor.fit(X_train,Y_train)

LinearRegression()

In [31]:
#coef_ method used to get the weight of the model
weight=regressor.coef_
weight

array([[9360.26128619]])

In [32]:
#intercept_ function is used to get the bias of the model
bias=regressor.intercept_
bias

array([26777.3913412])

In [30]:
#predict function will take input dataset and return the prediction
Y_predict=regressor.predict(X_test)
Y_predict

array([[ 40817.78327049],
       [123188.08258899],
       [ 65154.46261459],
       [ 63282.41035735],
       [115699.87356004],
       [108211.66453108],
       [116635.89968866],
       [ 64218.43648597],
       [ 76386.77615802]])

In [33]:
#import r2_score function from sklearn.metrics puthon library package
#r2_score will be used to validate the model
from sklearn.metrics import r2_score
#r2_score will compare the Output/to predict values from the original file with the output/prediction by the model and return the value between o and 1
#if r2_score value is near to 1, it is a good prediction
#if r2_score value is near to 0, it is a bad prediction
r_score=r2_score(Y_test,Y_predict)
r_score

0.9740993407213511

In [35]:
#pickle is a python library used to save the model in separate file
import pickle
filename="simple_linear_regression_model.sav"
#dump function in pickle is used to save the file. It will get model(regressor) and filedetails with writebyte as a input and save the model in the file
pickle.dump(regressor,open(filename,'wb'))

In [34]:
#load function in pickel is used to load the model. It will get filedetails with readbyte as a input and store the details in variable.
loaded_model=pickle.load(open(filename,'rb'))
#predict function can be used to predict the values from the model It will take values for which we need prediction.
result=loaded_model.predict([[15]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[167181.3106341]])